# ASP.NET Core (.NET Core)
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest' # Use the latest version of Ubuntu

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk' 
    version: '3.1.x'  # Adjust to your project's SDK version.
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet restore $(solution)
  displayName: 'DotNet Restore'

- script: dotnet build $(solution) --configuration $(buildConfiguration) --no-restore
  displayName: 'DotNet Build'

- script: dotnet publish $(solution) --configuration $(buildConfiguration) --output $(build.artifactStagingDirectory)/WebApp --no-build
  displayName: 'DotNet Publish'

- script: dotnet test $(solution) --configuration $(buildConfiguration) --no-build --no-restore
  displayName: 'DotNet Test'
